import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import { getSession } from "@/lib/session";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getSession();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav className="flex gap-4 border-b border-zinc-200 bg-white px-4 py-3 dark:border-zinc-800 dark:bg-zinc-900">
          <Link href="/" className="text-sm font-medium text-zinc-700 hover:underline dark:text-zinc-300">
            記帳紀錄
          </Link>
          <Link href="/board" className="text-sm font-medium text-zinc-700 hover:underline dark:text-zinc-300">
            留言板
          </Link>
          <Link href="/login" className="text-sm font-medium text-zinc-700 hover:underline dark:text-zinc-300">
            會員中心
          </Link>
          {session?.role === "admin" && (
            <Link href="/admin" className="text-sm font-medium text-zinc-700 hover:underline dark:text-zinc-300">
              後台管理
            </Link>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
